# Generated by Django 4.0.2 on 2022-08-09 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_article_explanation_alter_article_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Code', models.CharField(max_length=3000, verbose_name='code')),
                ('file', models.FileField(upload_to='', verbose_name='File')),
            ],
        ),
    ]
