# Generated by Django 4.0.2 on 2022-08-09 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_code_codemodel_code_codemodel_coder_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codemodel',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='media', verbose_name='Fayl elave edin'),
        ),
    ]
